{% set name = "ffmpeg-progress-yield" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slhck/ffmpeg-progress-yield/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9f7c472a2bbe8526df260cdeae021195e137c3efe9cd0a0e5c19179c4bba797d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ffmpeg-progress-yield = ffmpeg_progress_yield.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - tqdm >=4.38.0
    - colorama >=0.4.3

test:
  imports:
    - ffmpeg_progress_yield
  requires:
    - pip
  commands:
    - pip check
    - ffmpeg-progress-yield -h

about:
  home: https://github.com/slhck/ffmpeg-progress-yield
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Run an ffmpeg command with progress
  description: |
    Run an ffmpeg command with progress.
    An external installation of ffmpeg is reuqired.
  doc_url: https://github.com/slhck/ffmpeg-progress-yield/blob/master/README.md
  dev_url: https://github.com/slhck/ffmpeg-progress-yield/

extra:
  recipe-maintainers:
    - slhck
